ass_A : 
	g++ -o test ass_A.cpp
	./test
ass_C&D : 
	g++ -o test ass_C&D.cpp
	./test
ass_E : 
	g++ -o test ass_E.cpp
	./test
ass_F1 : 
	g++ -o test ass_F1.cpp
	./test
ass_F2 : 
	g++ -o test ass_F2.cpp
	./test
test1_B_spline : 
	g++ -o test test1_B_spline.cpp
	./test
test2_B_spline : 
	g++ -o test test2_B_spline.cpp
	./test
