ass_A : 
	g++ -o test ass_A.cpp
	./test
ass_C_D : 
	g++ -o test ass_C_D.cpp
	./test
ass_E : 
	g++ -o test ass_E.cpp
	./test

test1_B_spline : 
	g++ -o test test1_B_spline.cpp
	./test
test2_B_spline : 
	g++ -o test test2_B_spline.cpp
	./test
